
package org.troparo.source;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BusinessFaultType", targetNamespace = "http://troparo.org/entities/book")
public class BusinessException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BusinessException(String message, BusinessFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BusinessException(String message, BusinessFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.telusko.source.BusinessFaultType
     */
    public BusinessFaultType getFaultInfo() {
        return faultInfo;
    }

}
